#!/usr/bin/perl -w

use strict;

my $buf="";
my $crt="";
my $in=0;

while(<STDIN>) {
	next if /^#/;
	if(/^=+$/) {
		if($in) {
			print CRT $crt;
			close CRT;
			$buf=~s|/|-|g;
			$buf=~s|\n||;
			open CRT,">$buf.crt";
			$buf="";
			$crt="";
		} else {
			$buf=~s|/|-|g;
			$buf=~s|\n||;
			open CRT,">$buf.crt";
			$buf="";
			$in=1;
		}
	} else {
		$crt.=$buf;
		$buf=$_;
	}
}
print CRT $crt.$buf;
close CRT;
